name: Update TLD List

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-tld-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run make all to generate list
        run: make all

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add parser/public_suffix_list.go
          # Commit only if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Update public suffix list"
            git push
          else
            echo "No changes to commit."
          fi
